### ISSUE TITLE
Error in Dynamic Scenario 'DD1_28' using v3

### ISSUE THREAD

**Issue by abdullah-alahmadi** [DeepMIMO/DeepMIMO-matlab#12]
I keep receiving this error: 'Index in position 1 exceeds array bounds.'

The parameters are:
`params.scenario = 'DD1_28'; `
`params.scene_first = 1;`
`params.scene_last = 2000;`
`params.active_user_first = 1;`
`params.active_user_last = 1; `
`params.num_paths = 1; `
`params.active_BS = 4;`
`params.enable_Doppler = 1;`

Note: same error in Python version also

**Comment by umut-demirhan** [comment]
Hi @abdullah-alahmadi 

Can you make sure you are using the latest version from the website ([or here](https://github.com/DeepMIMO/DeepMIMO-matlab)) and share more details on this error. I am able to generate the data using these parameters.

**Comment by abdullah-alahmadi** [comment]
Thanks @umut-demirhan. It is working now
