### ISSUE TITLE
Wireless Insite setup file

### ISSUE THREAD

**Issue by bianch16** [DeepMIMO/DeepMIMO-matlab#4]
Dear Alkhateeb :
  I am an undergraduate student doing graduate diploma based on your dataset.  I am interested in doing indoor senerio simulations like what you do in 'I1_2p4' scenario, and I still have some puzzles when I read your descriptions in your paper, so I wonder if you could provide your wireless insite setup files for 'I1_2p4'?

**Comment by ShaCJ** [comment]
Hey @bianch16 did you get the setup file?

**Comment by aprilbian** [comment]
No, I didn't; I just used the .mat files for my simulations to finish my diploma.

**Comment by wozaimoyu** [comment]
I 'm use "O1_60GHZ"to get dataset,but only get 1*1 cell（in it only about 1*1struct） ,are you too？
