### ISSUE TITLE
long running time

### ISSUE THREAD

**Issue by wdevazelhes** [DeepMIMO/DeepMIMO-matlab#6]
Hi, I tried to run the 'O1_60' scenario with default parameters, but I am stuck at ``- Percent done: 0.0`` for several hours (even overnight).
I am doing something wrong or is the simulation very long to run ? 
I'm using Octave on my laptop (8 virtual cores and 16GB of RAM)

Thanks a lot !

**Comment by umut-demirhan** [comment]
This might be possibly due to the selected parameters (e.g., too many users). Also efficiency improvements are made to the new version.

Please try with the up-to-date version and let us know if there is still a problem.
