### ISSUE TITLE
"I1_2p4/I1_2p4.params.mat". No such file or directory

### ISSUE THREAD

**Issue by rashiisingh** [DeepMIMO/DeepMIMO-matlab#7]
Hi,

I am trying to load the file I1_2p4.params.mat stored relatively to file 'DeepMIMO_Dataset_Generator.m' at 'RayTracing Scenarios/I1_2p4/I1_2p4.params.mat'. But I get the following load error while doing that.

Error using load Unable to read file './RayTracing Scenarios/I1_2p4/I1_2p4.params.mat'. No such file or directory

I'm new to MATLAB but is this looks like a file not found error. Is the path relative or do I need to set some path explicitly?

Thanks,
Rashi

**Comment by umut-demirhan** [comment]
The issue is closed after the updates. Please try with the up-to-date version and let us know if there is still a problem.
