### ISSUE TITLE
Error the dynamic channel generation

### ISSUE THREAD

**Issue by JackokieZhao** [DeepMIMO/DeepMIMO-matlab#8]
Dear DeepMIMO authors:

The DeepMIMO project provides a vital contribution to the combination of wireless communication and machine learning.
But there are still several problems disturbing me in the dynamic scenario:
1. One user's channels for different time steps are always exactly the same. In my opinion, the problem is located at the function 'DeepMIMO_generator' in 'DeepMIMO_generator.m'. The scenario data is generated according to 'params_inner.scenario_files' in the function 'generate_data', but only the 'params.scenario_files' are modified for different scenarios.
2. Each user will always have multiple scenarios with a channel of 0. I really don't know the reason.

I am honored to write this feedback to improve the DeepMIMO project. 

Yours sincerely, Jiwei Zhao

-------------------------------------------------------------------------------------------------------------------------
Mobile: +86-13853203210
Email: jw_zhao@smail.nju.edu.cn
Address: School of electronic science and engineering, Nanjing University, 
Xianlin Avenue Nanjing No. 163 Electronic Building (Panzhong to floor) 210093

**Comment by JackokieZhao** [comment]
![image](https://user-images.githubusercontent.com/19789205/196013720-4a791a0b-159f-43f9-be1a-36c4f2663140.png)
The distribution of zero channel scenario indexes for approximately 500 users is shown here (every user has 500 scenarios).

**Comment by JackokieZhao** [comment]
The distribution of zero channel scenario indexes for approximately 500 users is shown here (every user has 500 scenarios).
![untitled1](https://user-images.githubusercontent.com/19789205/196013804-6f0356c5-615a-4b63-a1a7-5f06c479af82.png)

**Comment by umut-demirhan** [comment]
Hi @JackokieZhao 

Thanks for the comments.

The answers to the problems: 
1) The channels of the users are not strictly the same within each scene. This can only be the case if the ray-tracing data is the same within scenes (time), which may happen. 
For the next part of your question, the ray-tracing data for each scene is saved in separate files; hence, the files to be read and used for channel generation change at each scene. The non-changing parameters are the general parameters of the scenario, such as frequency, bandwidth, and antenna parameters, which stays constant for each dataset generation.
2) The channel is returned as zeroes if there is no channel paths. That should be the reason for this effect.

Also, if you let us know the specific user-BS-scene set that you think is problematic, we can check the data. I'm closing the issue for now.
